### ISSUE TITLE
Plugin not running with with java 16

### ISSUE THREAD

**Issue by ChMThiel** [jboz/living-documentation#79]
Hello,
using java 16 i get following warnings
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jruby.util.io.ChannelDescriptor (file:/home/christiant/.m2/repository/org/jruby/jruby-complete/1.7.26/jruby-complete-1.7.26.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of org.jruby.util.io.ChannelDescriptor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
but plugin is doing it's job.

Using java 16 it's no longer a warning, but the build fails:
```
2021-11-12T11:24:42.548+01:00: JavaProxyClassFactory: could not use ClassLoader.defineClass method
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @10b5e705
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.jruby.javasupport.proxy.JavaProxyClassFactory$1.run(JavaProxyClassFactory.java:231)
	at org.jruby.javasupport.proxy.JavaProxyClassFactory$1.run(JavaProxyClassFactory.java:224)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at org.jruby.javasupport.proxy.JavaProxyClassFactory.<clinit>(JavaProxyClassFactory.java:224)
	at org.jruby.javasupport.Java.load(Java.java:134)
	at org.jruby.runtime.load.LoadService.reflectedLoad(LoadService.java:598)
	at org.jruby.ext.LateLoadingLibrary.load(LateLoadingLibrary.java:48)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:51)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:892)
	at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:465)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:414)
	at org.jruby.ext.jruby.JRubyLibrary.load(JRubyLibrary.java:78)
	at org.jruby.runtime.load.LoadService.reflectedLoad(LoadService.java:598)
	at org.jruby.ext.LateLoadingLibrary.load(LateLoadingLibrary.java:48)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:51)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:892)
	at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:465)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:414)
	at org.jruby.Ruby.init(Ruby.java:1248)
	at org.jruby.Ruby.newInstance(Ruby.java:334)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:95)
	at org.asciidoctor.internal.JRubyAsciidoctor.createJRubyAsciidoctorInstance(JRubyAsciidoctor.java:119)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:62)
	at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:54)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:668)
	at ch.ifocusit.livingdoc.plugin.baseMojo.AbstractAsciidoctorMojo.createAsciidoctor(AbstractAsciidoctorMojo.java:113)
	at ch.ifocusit.livingdoc.plugin.baseMojo.AbstractAsciidoctorMojo.write(AbstractAsciidoctorMojo.java:100)
	at ch.ifocusit.livingdoc.plugin.baseMojo.AbstractDocsGeneratorMojo.write(AbstractDocsGeneratorMojo.java:121)
	at ch.ifocusit.livingdoc.plugin.baseMojo.AbstractDocsGeneratorMojo.write(AbstractDocsGeneratorMojo.java:117)
	at ch.ifocusit.livingdoc.plugin.DiagramMojo.executeMojo(DiagramMojo.java:174)
	at ch.ifocusit.livingdoc.plugin.baseMojo.AbstractAsciidoctorMojo.execute(AbstractAsciidoctorMojo.java:87)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time:  28.956 s
Finished at: 2021-11-12T11:24:47+01:00
------------------------------------------------------------------------
Failed to execute goal ch.ifocusit.livingdoc:livingdoc-maven-plugin:1.19:diagram (attribute-diagram) on project attribute: Execution attribute-diagram of goal ch.ifocusit.livingdoc:livingdoc-maven-plugin:1.19:diagram failed: An API incompatibility was encountered while executing ch.ifocusit.livingdoc:livingdoc-maven-plugin:1.19:diagram: java.lang.IllegalAccessError: class net.sourceforge.plantuml.png.PngIOMetadata (in unnamed module @0x3b2e6cf1) cannot access class com.sun.imageio.plugins.png.PNGMetadata (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.png to unnamed module @0x3b2e6cf1
-----------------------------------------------------
realm =    plugin>ch.ifocusit.livingdoc:livingdoc-maven-plugin:1.19
```
Any change of getting an update to make it run with current jdks?

**Comment by jboz** [comment]
migration done to java 17 with IT tests
